package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AddreessType generated by hbm2java
 */
public class AddreessType implements java.io.Serializable {

	private BigDecimal addressTypeId;
	private String addressTypeCode;
	private String addressTypeDescpription;
	private Set addresses = new HashSet(0);

	public AddreessType() {
	}

	public AddreessType(BigDecimal addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public AddreessType(BigDecimal addressTypeId, String addressTypeCode,
			String addressTypeDescpription, Set addresses) {
		this.addressTypeId = addressTypeId;
		this.addressTypeCode = addressTypeCode;
		this.addressTypeDescpription = addressTypeDescpription;
		this.addresses = addresses;
	}

	public BigDecimal getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(BigDecimal addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public String getAddressTypeCode() {
		return this.addressTypeCode;
	}

	public void setAddressTypeCode(String addressTypeCode) {
		this.addressTypeCode = addressTypeCode;
	}

	public String getAddressTypeDescpription() {
		return this.addressTypeDescpription;
	}

	public void setAddressTypeDescpription(String addressTypeDescpription) {
		this.addressTypeDescpription = addressTypeDescpription;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
