package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * AppRole generated by hbm2java
 */
public class AppRole implements java.io.Serializable {

	private BigDecimal appUserRoleId;
	private String appRoleCode;
	private String roleShortDescription;
	private String roleLongDescription;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date modifiedDate;
	private AppUserRole appUserRole;

	public AppRole() {
	}

	public AppRole(BigDecimal appUserRoleId) {
		this.appUserRoleId = appUserRoleId;
	}

	public AppRole(BigDecimal appUserRoleId, String appRoleCode,
			String roleShortDescription, String roleLongDescription,
			String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, AppUserRole appUserRole) {
		this.appUserRoleId = appUserRoleId;
		this.appRoleCode = appRoleCode;
		this.roleShortDescription = roleShortDescription;
		this.roleLongDescription = roleLongDescription;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.appUserRole = appUserRole;
	}

	public BigDecimal getAppUserRoleId() {
		return this.appUserRoleId;
	}

	public void setAppUserRoleId(BigDecimal appUserRoleId) {
		this.appUserRoleId = appUserRoleId;
	}

	public String getAppRoleCode() {
		return this.appRoleCode;
	}

	public void setAppRoleCode(String appRoleCode) {
		this.appRoleCode = appRoleCode;
	}

	public String getRoleShortDescription() {
		return this.roleShortDescription;
	}

	public void setRoleShortDescription(String roleShortDescription) {
		this.roleShortDescription = roleShortDescription;
	}

	public String getRoleLongDescription() {
		return this.roleLongDescription;
	}

	public void setRoleLongDescription(String roleLongDescription) {
		this.roleLongDescription = roleLongDescription;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public AppUserRole getAppUserRole() {
		return this.appUserRole;
	}

	public void setAppUserRole(AppUserRole appUserRole) {
		this.appUserRole = appUserRole;
	}

}
