package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * AppUserRole generated by hbm2java
 */
public class AppUserRole implements java.io.Serializable {

	private BigDecimal appUserRoleId;
	private AppRole appRole;
	private AppUser appUser;

	public AppUserRole() {
	}

	public AppUserRole(AppRole appRole, AppUser appUser) {
		this.appRole = appRole;
		this.appUser = appUser;
	}

	public BigDecimal getAppUserRoleId() {
		return this.appUserRoleId;
	}

	public void setAppUserRoleId(BigDecimal appUserRoleId) {
		this.appUserRoleId = appUserRoleId;
	}

	public AppRole getAppRole() {
		return this.appRole;
	}

	public void setAppRole(AppRole appRole) {
		this.appRole = appRole;
	}

	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

}
