package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AppUser generated by hbm2java
 */
public class AppUser implements java.io.Serializable {

	private BigDecimal appUserId;
	private String gender;
	private String firstName;
	private String middleName;
	private String lastName;
	private Set addresses = new HashSet(0);
	private Set orderses = new HashSet(0);
	private Set appUserRoles = new HashSet(0);

	public AppUser() {
	}

	public AppUser(BigDecimal appUserId) {
		this.appUserId = appUserId;
	}

	public AppUser(BigDecimal appUserId, String gender, String firstName,
			String middleName, String lastName, Set addresses, Set orderses,
			Set appUserRoles) {
		this.appUserId = appUserId;
		this.gender = gender;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.addresses = addresses;
		this.orderses = orderses;
		this.appUserRoles = appUserRoles;
	}

	public BigDecimal getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(BigDecimal appUserId) {
		this.appUserId = appUserId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	public Set getAppUserRoles() {
		return this.appUserRoles;
	}

	public void setAppUserRoles(Set appUserRoles) {
		this.appUserRoles = appUserRoles;
	}

}
