package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceStatusCode generated by hbm2java
 */
public class InvoiceStatusCode implements java.io.Serializable {

	private BigDecimal invoiceStatusCode;
	private String invoiceStatusDescription;
	private Set invoices = new HashSet(0);

	public InvoiceStatusCode() {
	}

	public InvoiceStatusCode(BigDecimal invoiceStatusCode) {
		this.invoiceStatusCode = invoiceStatusCode;
	}

	public InvoiceStatusCode(BigDecimal invoiceStatusCode,
			String invoiceStatusDescription, Set invoices) {
		this.invoiceStatusCode = invoiceStatusCode;
		this.invoiceStatusDescription = invoiceStatusDescription;
		this.invoices = invoices;
	}

	public BigDecimal getInvoiceStatusCode() {
		return this.invoiceStatusCode;
	}

	public void setInvoiceStatusCode(BigDecimal invoiceStatusCode) {
		this.invoiceStatusCode = invoiceStatusCode;
	}

	public String getInvoiceStatusDescription() {
		return this.invoiceStatusDescription;
	}

	public void setInvoiceStatusDescription(String invoiceStatusDescription) {
		this.invoiceStatusDescription = invoiceStatusDescription;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

}
