package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private BigDecimal invoiceNumber;
	private InvoiceStatusCode invoiceStatusCode;
	private Orders orders;
	private Date invoiceDate;
	private String invoiceDetails;
	private Set shipmentses = new HashSet(0);

	public Invoice() {
	}

	public Invoice(BigDecimal invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public Invoice(BigDecimal invoiceNumber,
			InvoiceStatusCode invoiceStatusCode, Orders orders,
			Date invoiceDate, String invoiceDetails, Set shipmentses) {
		this.invoiceNumber = invoiceNumber;
		this.invoiceStatusCode = invoiceStatusCode;
		this.orders = orders;
		this.invoiceDate = invoiceDate;
		this.invoiceDetails = invoiceDetails;
		this.shipmentses = shipmentses;
	}

	public BigDecimal getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(BigDecimal invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public InvoiceStatusCode getInvoiceStatusCode() {
		return this.invoiceStatusCode;
	}

	public void setInvoiceStatusCode(InvoiceStatusCode invoiceStatusCode) {
		this.invoiceStatusCode = invoiceStatusCode;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public String getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(String invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

	public Set getShipmentses() {
		return this.shipmentses;
	}

	public void setShipmentses(Set shipmentses) {
		this.shipmentses = shipmentses;
	}

}
