package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * OrderItems generated by hbm2java
 */
public class OrderItems implements java.io.Serializable {

	private BigDecimal orderItemId;
	private OrderItemsStatusCode orderItemsStatusCode;
	private Products products;
	private Orders orders;
	private BigDecimal orderItemsQuantity;
	private BigDecimal orderItemsPrice;
	private String otherOrderItemDetails;

	public OrderItems() {
	}

	public OrderItems(BigDecimal orderItemId) {
		this.orderItemId = orderItemId;
	}

	public OrderItems(BigDecimal orderItemId,
			OrderItemsStatusCode orderItemsStatusCode, Products products,
			Orders orders, BigDecimal orderItemsQuantity,
			BigDecimal orderItemsPrice, String otherOrderItemDetails) {
		this.orderItemId = orderItemId;
		this.orderItemsStatusCode = orderItemsStatusCode;
		this.products = products;
		this.orders = orders;
		this.orderItemsQuantity = orderItemsQuantity;
		this.orderItemsPrice = orderItemsPrice;
		this.otherOrderItemDetails = otherOrderItemDetails;
	}

	public BigDecimal getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(BigDecimal orderItemId) {
		this.orderItemId = orderItemId;
	}

	public OrderItemsStatusCode getOrderItemsStatusCode() {
		return this.orderItemsStatusCode;
	}

	public void setOrderItemsStatusCode(
			OrderItemsStatusCode orderItemsStatusCode) {
		this.orderItemsStatusCode = orderItemsStatusCode;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public BigDecimal getOrderItemsQuantity() {
		return this.orderItemsQuantity;
	}

	public void setOrderItemsQuantity(BigDecimal orderItemsQuantity) {
		this.orderItemsQuantity = orderItemsQuantity;
	}

	public BigDecimal getOrderItemsPrice() {
		return this.orderItemsPrice;
	}

	public void setOrderItemsPrice(BigDecimal orderItemsPrice) {
		this.orderItemsPrice = orderItemsPrice;
	}

	public String getOtherOrderItemDetails() {
		return this.otherOrderItemDetails;
	}

	public void setOtherOrderItemDetails(String otherOrderItemDetails) {
		this.otherOrderItemDetails = otherOrderItemDetails;
	}

}
