package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus implements java.io.Serializable {

	private BigDecimal orderStatusCode;
	private String orderStatusDescription;
	private Set orderses = new HashSet(0);

	public OrderStatus() {
	}

	public OrderStatus(BigDecimal orderStatusCode) {
		this.orderStatusCode = orderStatusCode;
	}

	public OrderStatus(BigDecimal orderStatusCode,
			String orderStatusDescription, Set orderses) {
		this.orderStatusCode = orderStatusCode;
		this.orderStatusDescription = orderStatusDescription;
		this.orderses = orderses;
	}

	public BigDecimal getOrderStatusCode() {
		return this.orderStatusCode;
	}

	public void setOrderStatusCode(BigDecimal orderStatusCode) {
		this.orderStatusCode = orderStatusCode;
	}

	public String getOrderStatusDescription() {
		return this.orderStatusDescription;
	}

	public void setOrderStatusDescription(String orderStatusDescription) {
		this.orderStatusDescription = orderStatusDescription;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
