package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private BigDecimal productId;
	private String productTypeCode;
	private String productName;
	private BigDecimal productPrize;
	private String productDescription;
	private Clob productImage;
	private Set orderItemses = new HashSet(0);

	public Products() {
	}

	public Products(BigDecimal productId) {
		this.productId = productId;
	}

	public Products(BigDecimal productId, String productTypeCode,
			String productName, BigDecimal productPrize,
			String productDescription, Clob productImage, Set orderItemses) {
		this.productId = productId;
		this.productTypeCode = productTypeCode;
		this.productName = productName;
		this.productPrize = productPrize;
		this.productDescription = productDescription;
		this.productImage = productImage;
		this.orderItemses = orderItemses;
	}

	public BigDecimal getProductId() {
		return this.productId;
	}

	public void setProductId(BigDecimal productId) {
		this.productId = productId;
	}

	public String getProductTypeCode() {
		return this.productTypeCode;
	}

	public void setProductTypeCode(String productTypeCode) {
		this.productTypeCode = productTypeCode;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public BigDecimal getProductPrize() {
		return this.productPrize;
	}

	public void setProductPrize(BigDecimal productPrize) {
		this.productPrize = productPrize;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public Clob getProductImage() {
		return this.productImage;
	}

	public void setProductImage(Clob productImage) {
		this.productImage = productImage;
	}

	public Set getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set orderItemses) {
		this.orderItemses = orderItemses;
	}

}
