package edu.ucmo.ase.sc.domain;

// default package
// Generated Oct 14, 2014 8:17:09 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Shipments generated by hbm2java
 */
public class Shipments implements java.io.Serializable {

	private BigDecimal shipmentId;
	private Invoice invoice;
	private Orders orders;
	private String shipmentTrackingNumber;
	private Date shipmentDate;

	public Shipments() {
	}

	public Shipments(BigDecimal shipmentId, Orders orders) {
		this.shipmentId = shipmentId;
		this.orders = orders;
	}

	public Shipments(BigDecimal shipmentId, Invoice invoice, Orders orders,
			String shipmentTrackingNumber, Date shipmentDate) {
		this.shipmentId = shipmentId;
		this.invoice = invoice;
		this.orders = orders;
		this.shipmentTrackingNumber = shipmentTrackingNumber;
		this.shipmentDate = shipmentDate;
	}

	public BigDecimal getShipmentId() {
		return this.shipmentId;
	}

	public void setShipmentId(BigDecimal shipmentId) {
		this.shipmentId = shipmentId;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public String getShipmentTrackingNumber() {
		return this.shipmentTrackingNumber;
	}

	public void setShipmentTrackingNumber(String shipmentTrackingNumber) {
		this.shipmentTrackingNumber = shipmentTrackingNumber;
	}

	public Date getShipmentDate() {
		return this.shipmentDate;
	}

	public void setShipmentDate(Date shipmentDate) {
		this.shipmentDate = shipmentDate;
	}

}
