--------------------------------------------------------
--  File created - Tuesday-October-14-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "ASE_ECOM_SC"."CUSTOMER_SEQUENCE"  MINVALUE 99001 MAXVALUE 99999 INCREMENT BY 1 START WITH 99001 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADDREESS_TYPE
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."ADDREESS_TYPE" 
   (	"ADDRESS_TYPE_ID" NUMBER, 
	"ADDRESS_TYPE_CODE" VARCHAR2(20 BYTE), 
	"ADDRESS_TYPE_DESCPRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."ADDRESS" 
   (	"ADDRESS_ID" NUMBER, 
	"APP_USER_ID" NUMBER, 
	"ADDRESS_LINE_1" VARCHAR2(20 BYTE), 
	"ADDREESS_LINE_2" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"ZIPCODE" VARCHAR2(20 BYTE), 
	"ADDRESS_TYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table APP_ROLE
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."APP_ROLE" 
   (	"APP_USER_ROLE_ID" NUMBER, 
	"APP_ROLE_CODE" VARCHAR2(20 BYTE), 
	"ROLE_SHORT_DESCRIPTION" VARCHAR2(20 BYTE), 
	"ROLE_LONG_DESCRIPTION" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table APP_USER
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."APP_USER" 
   (	"APP_USER_ID" NUMBER, 
	"GENDER" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"MIDDLE_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"ORDER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table APP_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."APP_USER_ROLE" 
   (	"APP_USER_ROLE_ID" NUMBER, 
	"APP_USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."INVOICE" 
   (	"INVOICE_NUMBER" NUMBER, 
	"ORDER_ID" NUMBER, 
	"INVOICE_STATUS_CODE" NUMBER, 
	"INVOICE_DATE" DATE, 
	"INVOICE_DETAILS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table INVOICE_STATUS_CODE
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."INVOICE_STATUS_CODE" 
   (	"INVOICE_STATUS_CODE" NUMBER, 
	"INVOICE_STATUS_DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_STATUS" VARCHAR2(20 BYTE), 
	"ORDER_PLACED_DATE" DATE, 
	"ORDER_DETAILS" VARCHAR2(20 BYTE), 
	"ORDER_STATUS_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."ORDER_ITEMS" 
   (	"ORDER_ITEM_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"ORDER_ITEMS_STATUS_CODE" NUMBER, 
	"ORDER_ITEMS_QUANTITY" NUMBER, 
	"ORDER_ITEMS_PRICE" NUMBER(*,0), 
	"OTHER_ORDER_ITEM_DETAILS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS_STATUS_CODE
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."ORDER_ITEMS_STATUS_CODE" 
   (	"ORDER_ITEMS_STATUS_CODE" NUMBER, 
	"ORDER_ITEMS_STATUS_DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table ORDER_STATUS
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."ORDER_STATUS" 
   (	"ORDER_STATUS_CODE" NUMBER, 
	"ORDER_STATUS_DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_TYPE_CODE" VARCHAR2(20 BYTE), 
	"PRODUCT_NAME" VARCHAR2(20 BYTE), 
	"PRODUCT_PRIZE" NUMBER, 
	"PRODUCT_DESCRIPTION" VARCHAR2(20 BYTE), 
	"PRODUCT_IMAGE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" 
 LOB ("PRODUCT_IMAGE") STORE AS BASICFILE (
  TABLESPACE "TBS_ECOM_SC_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SHIPMENTS
--------------------------------------------------------

  CREATE TABLE "ASE_ECOM_SC"."SHIPMENTS" 
   (	"SHIPMENT_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"INVOICE_NUMBER" NUMBER, 
	"SHIPMENT_TRACKING_NUMBER" VARCHAR2(20 BYTE), 
	"SHIPMENT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index ADDREESS_TYPE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."ADDREESS_TYPE_PK1" ON "ASE_ECOM_SC"."ADDREESS_TYPE" ("ADDRESS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."ADDRESS_PK" ON "ASE_ECOM_SC"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index APP_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."APP_ROLE_PK" ON "ASE_ECOM_SC"."APP_ROLE" ("APP_USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index APP_USER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."APP_USER_ROLE_PK" ON "ASE_ECOM_SC"."APP_USER_ROLE" ("APP_USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."CUSTOMER_PK" ON "ASE_ECOM_SC"."APP_USER" ("APP_USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index INVOICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."INVOICE_PK" ON "ASE_ECOM_SC"."INVOICE" ("INVOICE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index INVOICE_STATUS_CODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."INVOICE_STATUS_CODE_PK" ON "ASE_ECOM_SC"."INVOICE_STATUS_CODE" ("INVOICE_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."ORDERS_PK" ON "ASE_ECOM_SC"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index ORDER_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."ORDER_ITEMS_PK" ON "ASE_ECOM_SC"."ORDER_ITEMS" ("ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index ORDER_ITEMS_STATUS_CODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."ORDER_ITEMS_STATUS_CODE_PK" ON "ASE_ECOM_SC"."ORDER_ITEMS_STATUS_CODE" ("ORDER_ITEMS_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index ORDER_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."ORDER_STATUS_PK" ON "ASE_ECOM_SC"."ORDER_STATUS" ("ORDER_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."PRODUCTS_PK" ON "ASE_ECOM_SC"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  DDL for Index SHIPMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASE_ECOM_SC"."SHIPMENT_PK" ON "ASE_ECOM_SC"."SHIPMENTS" ("SHIPMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01" ;
--------------------------------------------------------
--  Constraints for Table ADDREESS_TYPE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ADDREESS_TYPE" MODIFY ("ADDRESS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."ADDREESS_TYPE" ADD CONSTRAINT "ADDREESS_TYPE_PK" PRIMARY KEY ("ADDRESS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ADDRESS" MODIFY ("APP_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."ADDRESS" MODIFY ("ADDRESS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APP_ROLE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."APP_ROLE" ADD CONSTRAINT "APP_ROLE_PK" PRIMARY KEY ("APP_USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."APP_ROLE" MODIFY ("APP_USER_ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."APP_USER" ADD CONSTRAINT "APP_USER_PK" PRIMARY KEY ("APP_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."APP_USER" MODIFY ("APP_USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."APP_USER_ROLE" ADD CONSTRAINT "APP_USER_ROLE_PK" PRIMARY KEY ("APP_USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."APP_USER_ROLE" MODIFY ("APP_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."APP_USER_ROLE" MODIFY ("APP_USER_ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."INVOICE" ADD CONSTRAINT "INVOICE_PK" PRIMARY KEY ("INVOICE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."INVOICE" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICE_STATUS_CODE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."INVOICE_STATUS_CODE" ADD CONSTRAINT "INVOICE_STATUS_CODE_PK" PRIMARY KEY ("INVOICE_STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."INVOICE_STATUS_CODE" MODIFY ("INVOICE_STATUS_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."ORDERS" MODIFY ("ORDER_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS_STATUS_CODE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS_STATUS_CODE" ADD CONSTRAINT "ORDER_ITEMS_STATUS_CODE_PK" PRIMARY KEY ("ORDER_ITEMS_STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS_STATUS_CODE" MODIFY ("ORDER_ITEMS_STATUS_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_STATUS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ORDER_STATUS" MODIFY ("ORDER_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."ORDER_STATUS" ADD CONSTRAINT "ORDER_STATUS_PK" PRIMARY KEY ("ORDER_STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHIPMENTS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."SHIPMENTS" ADD CONSTRAINT "SHIPMENT_PK" PRIMARY KEY ("SHIPMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ECOM_SC_01"  ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."SHIPMENTS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASE_ECOM_SC"."SHIPMENTS" MODIFY ("SHIPMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK1" FOREIGN KEY ("ADDRESS_TYPE_ID")
	  REFERENCES "ASE_ECOM_SC"."ADDREESS_TYPE" ("ADDRESS_TYPE_ID") ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK2" FOREIGN KEY ("APP_USER_ID")
	  REFERENCES "ASE_ECOM_SC"."APP_USER" ("APP_USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."APP_USER" ADD CONSTRAINT "APP_USER_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ASE_ECOM_SC"."ORDERS" ("ORDER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."APP_USER_ROLE" ADD CONSTRAINT "APP_USER_ROLE_FK1" FOREIGN KEY ("APP_USER_ID")
	  REFERENCES "ASE_ECOM_SC"."APP_USER" ("APP_USER_ID") ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."APP_USER_ROLE" ADD CONSTRAINT "APP_USER_ROLE_FK2" FOREIGN KEY ("APP_USER_ROLE_ID")
	  REFERENCES "ASE_ECOM_SC"."APP_ROLE" ("APP_USER_ROLE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."INVOICE" ADD CONSTRAINT "INVOICE_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ASE_ECOM_SC"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."INVOICE" ADD CONSTRAINT "INVOICE_FK2" FOREIGN KEY ("INVOICE_STATUS_CODE")
	  REFERENCES "ASE_ECOM_SC"."INVOICE_STATUS_CODE" ("INVOICE_STATUS_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ORDERS" ADD CONSTRAINT "ORDERS_FK1" FOREIGN KEY ("ORDER_STATUS_CODE")
	  REFERENCES "ASE_ECOM_SC"."ORDER_STATUS" ("ORDER_STATUS_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ASE_ECOM_SC"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_FK2" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ASE_ECOM_SC"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_FK3" FOREIGN KEY ("ORDER_ITEMS_STATUS_CODE")
	  REFERENCES "ASE_ECOM_SC"."ORDER_ITEMS_STATUS_CODE" ("ORDER_ITEMS_STATUS_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHIPMENTS
--------------------------------------------------------

  ALTER TABLE "ASE_ECOM_SC"."SHIPMENTS" ADD CONSTRAINT "SHIPMENTS_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ASE_ECOM_SC"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "ASE_ECOM_SC"."SHIPMENTS" ADD CONSTRAINT "SHIPMENTS_FK2" FOREIGN KEY ("INVOICE_NUMBER")
	  REFERENCES "ASE_ECOM_SC"."INVOICE" ("INVOICE_NUMBER") ENABLE;
